name: Cleanup old workflow runs

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs older than 7 days
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 3
          # For a first trial run, set dry_run: true to see what would be deleted.
          # dry_run: true
